(provide 'keybindings-config)
(bind-keys*
 ("ESC ESC" . prot-simple-keyboard-quit-dwim)
 ("C-g" . prot-simple-keyboard-quit-dwim)
 ("C-t . f" . find-file)
 ("C-t . c" . comment-region)
 ("C-t . u" . uncomment-region)
 ("M-j" . avy-goto-char-timer)
 ("C-t j" . avy-goto-char)
 ("C-t w" . avy-goto-word-0)
 ("C-t l" . avy-goto-line)

 ("C-t b c" . clone-indirect-buffer)
 ("C-t b C" . clone-indirect-buffer-other-window)
 ("C-t b k" . kill-this-buffer)
 ("C-t b K" . kill-some-buffers)
 ("C-t b n" . next-buffer)
 ("C-t b p" . previous-buffer)
 ("C-t b r" . revert-buffer)
 ("C-t b R" . rename-buffer)
 ("C-t b s" . basic-save-buffer)
 ("C-t b S" . save-some-buffers)

 ("C-t r" . consult-recent-files)
 ("C-c C-b" . consult-buffer)
 ("C-t B b" . consult-bookmark)
 ("C-t h t" . consult-theme)
 ("C-t s r" . consult-ripgrep)
 ("C-t s g" . consult-grep)
 ("C-t s G" . consult-git-grep)
 ("C-t s f" . consult-find)
 ("C-t s F" . consult-locate)
 ("C-t s y" . consult-yank-from-kill-ring)
 ("C-t i" . consult-imenu)
 )

